name: Remove Deployment
on:
  workflow_dispatch:
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  deploy:
    # We don't want to remove protected deployment
    if: github.ref_protected == false
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: "./.github/actions/setup_node_and_pnpm"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ github.ref == 'refs/heads/master' && 'CHANGE_ME' || 'CHANGE_ME' }}
          aws-region: eu-central-1 # Is not related to deployment region
          role-session-name: CHANGE_ME

      - name: Remove
        run: mise sst remove
